// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
import { z } from "npm:zod@^3.25.76";
var search_products_default = defineTool({
  name: "search_products",
  title: "Pesquisar produtos",
  description: "Pesquisa produtos activos no marketplace AngoExpress por palavras-chave, categoria e pre\xE7o m\xE1ximo (em Kz).",
  inputSchema: {
    query: z.string().optional().describe("Palavras-chave a procurar no t\xEDtulo/descri\xE7\xE3o."),
    category: z.string().optional().describe("Nome da categoria a filtrar."),
    maxPrice: z.number().positive().optional().describe("Pre\xE7o m\xE1ximo em Kwanzas."),
    limit: z.number().int().min(1).max(20).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, maxPrice, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    let q = supabase.from("products").select("id,title,price,category,description").eq("is_active", true).limit(limit);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.ilike("category", `%${category}%`);
    if (maxPrice) q = q.lte("price", maxPrice);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Obter produto",
  description: "Devolve detalhes completos de um produto do AngoExpress pelo seu ID.",
  inputSchema: {
    id: z2.string().describe("ID do produto.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("products").select("id,title,price,category,description,seller_id,product_media(url,is_cover)").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Produto n\xE3o encontrado" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.1";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Listar categorias",
  description: "Lista todas as categorias distintas dos produtos activos no AngoExpress.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY
    );
    const { data, error } = await supabase.from("products").select("category").eq("is_active", true).limit(500);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const categories = Array.from(new Set((data ?? []).map((r) => r.category).filter(Boolean))).sort();
    return {
      content: [{ type: "text", text: JSON.stringify(categories, null, 2) }],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "angoexpress-mcp",
  title: "AngoExpress Marketplace",
  version: "0.1.0",
  instructions: "Ferramentas para pesquisar produtos, obter detalhes e listar categorias do marketplace AngoExpress (Angola).",
  tools: [search_products_default, get_product_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
